# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-14 07:32
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('pathmapperapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UpdateManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locationLastUpdate', models.DateTimeField(auto_now_add=True)),
                ('plantLastUpdate', models.DateTimeField(auto_now_add=True)),
                ('collectionLastUpdate', models.DateTimeField(auto_now_add=True)),
                ('plantCollectionLastUpdate', models.DateTimeField(auto_now_add=True)),
                ('trackLastUpdate', models.DateTimeField(auto_now_add=True)),
                ('trackPointLastUpdate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='track',
            name='name',
            field=models.CharField(default=datetime.datetime(2016, 5, 14, 7, 32, 12, 927040, tzinfo=utc), max_length=200),
            preserve_default=False,
        ),
    ]
